name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install
      
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
      
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install
      
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test
      
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to Server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
          cd /path/to/your/project &&
          git pull origin main &&
          docker-compose down &&
          docker-compose up -d --build
        ' 